### PR TITLE
Use f(Gemfile, Gemfile.lock) to determine layer reuse

### LINKED ISSUE #93: The buildpack should error if the Gemfile and Gemfile.lock are out of sync.
I updated the puma gem in my `Gemfile` but didn't update the `Gemfile.lock` and the buildpack reused the cache without erroring:
```
Paketo Bundle Install Buildpack 0.0.59
  Reusing cached layer /layers/paketo-buildpacks_bundle-install/gems
```

I expect that it either:
- Errors because the Gemfile.lock is out of sync; or
- Rebuilds the layer

### PR DESCRIPTION
**Pull request by arjun024**
- Also fail detect when Gemfile is not present as bundle install is irrelevant without Gemfile.
- Upate to packit v0.4.0 to use fs.ChecksumCalculator.Sum(...string)

Resolves #93 

--
Please confirm the following:
* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have added an integration test, if necessary.

### CODE REVIEW

**Comment by sophiewigmore** [comment]
The changes work as expected: if I make a change to a gem in my `Gemfile` without updating my `Gemfile.lock`, the buildpack rebuilds the layer rather than reusing the cached layer. 

This makes for an easier user experience, but do you think it would be better for clarity to error out if the `Gemfile` and `Gemfile.lock` are out of sync rather than using what's in the `Gemfile`? Also @ryanmoran what are your thoughts?

**Comment by arjun024** [comment]
@sophiewigmore I believe a buildpack shouldn't make such decisions and should be left to the logic of the tool. See [bundle install man page](https://bundler.io/man/bundle-install.1.html#DESCRIPTION) - It has its own logic to deal with contents of Gemfile and Gemfile.lock. The buildpack should only reuse built layer as an optimization when it's assured there would be no change in the build output.

**Comment by ryanmoran** [comment]
I agree with @arjun024. The use of the cache is for performance, not correctness. The correct behavior is to allow the tool to do what it would normally do in this case without intervention.

**Comment by sophiewigmore** [comment]
@arjun024 that makes sense, thanks for the explanation.

**Review by sophiewigmore — APPROVED** [review]

**Pull request merged**
